"""
================================================================================
                    BUILD EXECUTABLE SCRIPT FOR MEDICINE ERP
================================================================================

Purpose:
    This script builds a portable executable (.exe) from the Medicine ERP
    Python application. The resulting .exe can be run on any Windows PC
    without requiring Python installation.

Usage:
    python build_exe.py

What it does:
    1. Installs PyInstaller if not already installed
    2. Creates a PyInstaller spec file (Medicine_ERP.spec)
    3. Builds the executable
    4. Creates dist_package folder with all required files:
        - Medicine_ERP.exe
        - logo.ico
        - customer_bills/ folder
        - data/ folder with Excel files

Requirements:
    - Python 3.x installed
    - All dependencies in requirements.txt installed:
        pip install pandas openpyxl reportlab tkcalendar pyperclip pyinstaller

Output:
    - dist/Medicine_ERP.exe (raw executable)
    - dist_package/Medicine_ERP.exe (portable package)

Author: Medicine ERP Development Team
Version: 1.0
"""

import sys
import subprocess
import os
import shutil

# ================================================================================
# CONFIGURATION
# ================================================================================

# Project name
APP_NAME = "Medicine_ERP"
PACKAGE_NAME = "Gita Medical Hall ERP"

# Main application file
APP_FILE = "app.py"

# Icon file
ICON_FILE = "logo.ico"

# Data folders to include in executable
DATA_FOLDERS = [
    ('data', 'data'),
    ('customer_bills', 'customer_bills'),
]

# Hidden imports - modules that PyInstaller might miss
HIDDEN_IMPORTS = [
    'pandas',
    'openpyxl',
    'reportlab',
    'tkcalendar',
    'tk',
    'pyperclip',
    'PIL',
    'PIL._tkinter_finder',
    'tkinter',
    'tkinter.ttk',
    'tkinter.messagebox',
    'tkinter.filedialog',
    'openpyxl.workbook',
    'openpyxl.worksheet',
    'reportlab.lib',
    'reportlab.lib.pagesizes',
    'reportlab.pdfgen',
    'datetime',
    'pandas.core',
]

# ================================================================================
# FUNCTIONS
# ================================================================================

def is_package_installed(package_name):
    """
    Check if a Python package is installed.
    
    Args:
        package_name: Name of the package to check
        
    Returns:
        True if installed, False otherwise
    """
    result = subprocess.run(
        [sys.executable, "-m", "pip", "show", package_name],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )
    return result.returncode == 0


def install_package(package_name):
    """
    Install a Python package using pip.
    
    Args:
        package_name: Name of the package to install
    """
    print(f"Installing {package_name}...")
    subprocess.check_call([
        sys.executable, 
        "-m", 
        "pip", 
        "install", 
        package_name
    ])


def install_requirements():
    """
    Install PyInstaller if not already installed.
    Also installs other required packages if missing.
    """
    # Check and install PyInstaller
    if not is_package_installed("pyinstaller"):
        install_package("pyinstaller")
    else:
        print("✓ PyInstaller already installed")
    
    # Check other requirements
    requirements = ['pandas', 'openpyxl', 'reportlab', 'tkcalendar', 'pyperclip']
    for req in requirements:
        if not is_package_installed(req):
            install_package(req)
        else:
            print(f"✓ {req} already installed")


def get_current_directory():
    """
    Get the directory where this script is located.
    
    Returns:
        Absolute path to the script directory
    """
    return os.path.dirname(os.path.abspath(__file__))


def create_spec_file():
    """
    Create the PyInstaller spec file.
    
    The spec file tells PyInstaller how to build the executable,
    including what data files to include and what hidden imports to add.
    """
    current_dir = get_current_directory()
    
    # Build datas list as string
    datas_str = ""
    for src, dst in DATA_FOLDERS:
        datas_str += f"        ('{src}', '{dst}'),\n"
    
    # Build hidden imports string
    hidden_imports_str = ""
    for imp in HIDDEN_IMPORTS:
        hidden_imports_str += f"        '{imp}',\n"
    
    spec_content = f'''# -*- mode: python ; coding: utf-8 -*-
# This file is auto-generated by build_exe.py
# Do not edit manually unless you know what you're doing

block_cipher = None

a = Analysis(
    ['{APP_FILE}'],
    pathex=[],
    binaries=[],
    datas=[
{datas_str}    ],
    hiddenimports=[
{hidden_imports_str}    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='{APP_NAME}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='{ICON_FILE}',
)
'''
    
    spec_file_path = os.path.join(current_dir, f"{APP_NAME}.spec")
    with open(spec_file_path, "w") as f:
        f.write(spec_content)
    
    print(f"✓ Created {APP_NAME}.spec")


def run_pyinstaller():
    """
    Run PyInstaller to build the executable.
    """
    current_dir = get_current_directory()
    
    print("\nBuilding executable...")
    print("This may take a few minutes...")
    
    # Run PyInstaller with spec file
    result = subprocess.run(
        [sys.executable, "-m", "PyInstaller", f"{APP_NAME}.spec"],
        cwd=current_dir,
        capture_output=True,
        text=True
    )
    
    if result.returncode != 0:
        print("ERROR: Build failed!")
        print(result.stderr)
        return False
    
    print("✓ Build completed successfully!")
    return True


def create_dist_package():
    """
    Create the final distribution package with all required files.
    
    The package includes:
    - Medicine_ERP.exe
    - logo.ico
    - customer_bills/ folder
    - data/ folder with all Excel files
    """
    current_dir = get_current_directory()
    dist_dir = os.path.join(current_dir, "dist")
    pkg_dir = os.path.join(current_dir, PACKAGE_NAME)
    
    print("\nCreating distribution package...")
    
    # Remove existing package if exists
    if os.path.exists(pkg_dir):
        print("  Removing existing package...")
        shutil.rmtree(pkg_dir)
    
    # Create new package directory
    os.makedirs(pkg_dir)
    os.makedirs(os.path.join(pkg_dir, "customer_bills"))
    
    print("  ✓ Created dist_package/ structure")
    
    # Copy executable
    exe_source = os.path.join(dist_dir, f"{APP_NAME}.exe")
    if os.path.exists(exe_source):
        shutil.copy2(exe_source, os.path.join(pkg_dir, f"{APP_NAME}.exe"))
        print(f"  ✓ Copied {APP_NAME}.exe")
    else:
        print(f"  ✗ ERROR: {APP_NAME}.exe not found in dist/")
        return False
    
    # Copy logo
    logo_source = os.path.join(current_dir, ICON_FILE)
    if os.path.exists(logo_source):
        shutil.copy2(logo_source, os.path.join(pkg_dir, ICON_FILE))
        print(f"  ✓ Copied {ICON_FILE}")
    
    # Copy data folder
    data_source = os.path.join(current_dir, "data")
    data_dest = os.path.join(pkg_dir, "data")
    if os.path.exists(data_source):
        # Copy each Excel file
        if not os.path.exists(data_dest):
            os.makedirs(data_dest)
        for file in os.listdir(data_source):
            src = os.path.join(data_source, file)
            if os.path.isfile(src):
                shutil.copy2(src, data_dest)
        print("  ✓ Copied data/ folder")
    
    # Copy existing customer bills if any
    bills_source = os.path.join(current_dir, "customer_bills")
    bills_dest = os.path.join(pkg_dir, "customer_bills")
    if os.path.exists(bills_source):
        for file in os.listdir(bills_source):
            src = os.path.join(bills_source, file)
            if os.path.isfile(src):
                shutil.copy2(src, bills_dest)
        print("  ✓ Copied existing customer bills")
    
    # Create README
    readme_content = f"""# Medicine ERP - Portable Package

This folder contains the portable version of Medicine ERP.

INSTRUCTIONS:
1. Copy this entire folder to your target PC
2. Keep all files and folders in the same location as the .exe file
3. Run '{APP_NAME}.exe' to start the application
4. No Python installation required on the target PC!

FOLDER STRUCTURE:
- {APP_NAME}.exe     - Main application
- {ICON_FILE}             - Application icon
- customer_bills/      - Stores PDF bills
- data/                - Excel database files
  - customer_details.xlsx
  - store_details.xlsx
  - customer_bills.xlsx
  - distributor_details.xlsx
  - distributor_transactions.xlsx
  - credit_debit.xlsx


NOTE: 
- The first time you run, it may take a few seconds to initialize.
- Keep the folder structure intact for proper functioning.
- All data is stored in the Excel files within the data/ folder.
"""
    
    readme_path = os.path.join(pkg_dir, "README.txt")
    with open(readme_path, "w") as f:
        f.write(readme_content)
    print("  ✓ Created README.txt")
    
    return True


def cleanup_build_files():
    """
    Clean up temporary build files after successful build.
    """
    current_dir = get_current_directory()
    
    print("\nCleaning up build files...")
    
    # Remove build folder
    build_dir = os.path.join(current_dir, "build")
    if os.path.exists(build_dir):
        shutil.rmtree(build_dir)
        print("  ✓ Removed build/")
    
    # Remove dist folder (we have dist_package)
    dist_dir = os.path.join(current_dir, "dist")
    if os.path.exists(dist_dir):
        shutil.rmtree(dist_dir)
        print("  ✓ Removed dist/")
    
    # Remove spec file
    spec_file = os.path.join(current_dir, f"{APP_NAME}.spec")
    if os.path.exists(spec_file):
        os.remove(spec_file)
        print(f"  ✓ Removed {APP_NAME}.spec")
    
    print("✓ Cleanup complete!")


# ================================================================================
# MAIN FUNCTION
# ================================================================================

def main():
    """
    Main build process.
    
    Steps:
    1. Install requirements
    2. Create spec file
    3. Run PyInstaller
    4. Create distribution package
    5. Cleanup temporary files
    """
    print("=" * 70)
    print(f"       BUILDING {APP_NAME} EXECUTABLE")
    print("=" * 70)
    print()
    
    try:
        # Step 1: Install requirements
        print("Step 1: Checking dependencies...")
        install_requirements()
        
        # Step 2: Create spec file
        print("\nStep 2: Creating spec file...")
        create_spec_file()
        
        # Step 3: Run PyInstaller
        print("\nStep 3: Building executable...")
        if not run_pyinstaller():
            print("\nBuild failed! Please check errors above.")
            return
        
        # Step 4: Create distribution package
        print("\nStep 4: Creating distribution package...")
        if not create_dist_package():
            print("\nFailed to create distribution package!")
            return
        
        # Step 5: Cleanup
        print("\nStep 5: Cleaning up...")
        cleanup_build_files()
        
        # Success!
        print()
        print("=" * 70)
        print("  ✓ BUILD COMPLETED SUCCESSFULLY!")
        print("=" * 70)
        print()
        print(f"Output location: {PACKAGE_NAME}/")
        print()
        print("To deploy:")
        print(f"  1. Copy the entire '{PACKAGE_NAME}' folder")
        print(f"  2. Transfer to target PC")
        print(f"  3. Run {APP_NAME}.exe")
        print()
        
    except KeyboardInterrupt:
        print("\n\nBuild cancelled by user.")
    except Exception as e:
        print(f"\n\nError: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
